### ISSUE TITLE
Allow Client to operate from completely different system than server

### ISSUE THREAD

**Issue by gregg56** [pstavirs/ostinato#156]
Apologize if this is a duplicate, but did not see an issue that looked similar.

I have a CentOS 7 server that I want to run the Ostinato server on, but I want to be able to control said Ostinato server from a completely different machine (MAC / Windows / Linux), potentially, on a different network segment.

As a client server type of application this would seem to be a reasonable request.  I recognize that the Ostinato client wants to look at the local machine configuration upon loading and that is no problem.  What I am asking is to have the ability to pre-define a set of Ostinato server machines in the client that it can control nad have the ability to select from the list.

This would definitely be an Enhancement request.

Thank You,

Greg Guldenschuh

**Comment by pstavirs** [comment]
This has been supported since day 1 - see https://github.com/pstavirs/ostinato/wiki/UserGuide#ports-list

Or maybe I misunderstand what you are asking for?

**Comment by pstavirs** [comment]
No response for almost 2 months. Assuming invalid issue.
