### ISSUE TITLE
updating the freebsd port: PR 203507

### ISSUE THREAD

**Issue by opsec** [pstavirs/ostinato#159]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203507

has an update, FYI.

**Comment by pstavirs** [comment]
Thanks for taking the initiative to update the freebsd port.

If you need any help/support from upstream, do let us know. 

PS - you might also want to update the pkg-descr with the new home page - http://ostinato.org instead of the old GoogleCode URL

**Comment by pstavirs** [comment]
FreeBSD downstream has committed the latest package. Thanks!
