### ISSUE TITLE
Automatic detection of deleted/added interface

### ISSUE THREAD

**Issue by dlafleur6851** [pstavirs/ostinato#161]
Enhancement - Feature Request

In certain environment, the tap interfaces can be deleted/created dynamically. In order to see the new configuration, the drone has to be restarted which causes traffic interruption on the other interfaces. Also, the ports/streams have to be reconfigured, etc...

It would be great to have an automatic detection of deleted/added interfaces. A user provided refresh would also be good.

The deleted interfaces could become grayed (and unselectable). This would allow to keep the streams configured against the interface (i.e. when the interface is deleted and recreated).

**Comment by pstavirs** [comment]
Discussion on this use case - https://groups.google.com/forum/#!topic/ostinato/eG-PMH7k_qI

**Comment by pstavirs** [comment]
Unless someone can pitch a strong case for this, I don't intend to implement this. Closing for now.
