### ISSUE TITLE
problem in saving stream as python script for unimplemented protocols like GRE, MPLS... 

### ISSUE THREAD

**Issue by nmchowdary** [pstavirs/ostinato#170]
I am importing PCAP file having MPLS protocol, as MPLS protocol is not available, ostinato treats MPLS as a hexdump and it is decoding layers above MPLS properly.
Through ostinato GUI i am able to send packets properly  and in wireshark capture i am be able to see all the headers including MPLS properly.
But when i save it as python script, MPLS header is dumped as hex field and content for that field is exported as empty.(snippt of python script pasted below )

##########
    p.protocol_id.id = ost_pb.Protocol.kHexDumpFieldNumber
    p.Extensions[hexDump].content = ''
    p.Extensions[hexDump].pad_until_end = False
##########

Note : same problem observed for all unimplemented protocols like GRE, GTP...

**Comment by pstavirs** [comment]
Originally reported on the mailing list - https://groups.google.com/forum/#!topic/ostinato/IMSZKc2pMyQ
