### ISSUE TITLE
Qt5 support

### ISSUE THREAD

**Issue by pstavirs** [pstavirs/ostinato#173]
Qt4.8 LTS support will end in end of 2015 (http://blog.qt.io/blog/2015/12/18/introducing-long-term-support/), we need to consider moving to Qt5

Updates:
2017-01-03: Homebrew has dropped qt4 packages as well
2017-01-03: Qt 5 does not support OS X on PowerPC [1] (Current OSX development, packaging and support is done using an old PPC based Mac Mini)

Refs
[1]: http://doc.qt.io/qt-5/osx.html

**Comment by jungle-boogie** [comment]
Any plans for 2017 to switch to qt5?

**Comment by pstavirs** [comment]
@jungle-boogie yes the upgrade to qt5 will happen some time in 2017 most likely - have postponed it long enough. May have to drop/suspend OSX support though - Qt5 is not supported on my PPC based Mac Mini (on loan from a generous supporter!)

**Comment by ehlers** [comment]
Travis CI might be a way to create the package for OS X.
https://docs.travis-ci.com/user/reference/osx/

I'm owning an iMac running on 10.11 (El Capitan), so I can support as well.

**Comment by pstavirs** [comment]
@ehlers: Thanks for the offer! Plan to get this done post the 0.9 release. Will get in touch with you.

**Comment by kartikm** [comment]
See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=875077

**Comment by hprem** [comment]
I have been using ostinato on tinycore linux and that too has dropped support for qt4. Would be better if you could add support for qt5 soon

**Comment by ehlers** [comment]
The latest TinyCore Linux v8.2.1 has still QT4 support. The official virtual appliance and the live CD/DVD is based on TinyCore V8.2 as well as my Ostinato image for GNS3.

**Comment by hprem** [comment]
You are right. Tinycore now has qt4 libs. But when I looked last time (when 8.2 was released), it had qt4 libs only for the x86 (32 bit) repo and not on the x86_64 repo

**Comment by pstavirs** [comment]
Ostinato has been ported to Qt5. Intention is to have minimum Qt version as 5.9LTS. However, Travis is currently using Qt 5.2, so for now this is the minimum version - but this will change as soon as Travis supports a higher Qt version. So consider Qt5.9LTS as the minimum version

Please note Ostinato will now build only with Qt5, not with Qt4 - there is no intention to support Qt4 now.

**Comment by kartikm** [comment]
I don't see release tag of new version though, https://github.com/pstavirs/ostinato/releases

**Comment by pstavirs** [comment]
The code has been changed, but a new release has not been made.

No date yet for the new release.
