### ISSUE TITLE
doesn't show any ports when I run Ostinato on macbook pro

### ISSUE THREAD

**Issue by kurdok** [pstavirs/ostinato#176]
when i try to open Ostinato on my macbook pro is show this alert and doesn't show any ports. I also run drone app, but still no ports.
what should I do ? any help thanks.

<img width="623" alt="screen shot 2016-04-06 at 11 04 02 am" src="https://cloud.githubusercontent.com/assets/18303012/14309926/e3831cb6-fbe7-11e5-879b-e5a323eeccd7.png">

**Comment by pstavirs** [comment]
See https://github.com/pstavirs/ostinato/wiki/FAQ#q-i-dont-see-any-ports-in-my-port-list--q-im-unable-to-expand-the-port-group--q-port-group-has-no-interfaces

Keeping this issue open to fix the URL
