### ISSUE TITLE
deleteStream Python API is not deleting stream cleanly

### ISSUE THREAD

**Issue by johcheun** [pstavirs/ostinato#179]
With Ostinato 0.7.0, I noticed that after deleteStream is called in Python, the stream is deleted from the GUI (after reconnect / connect).  However, when trying to transmit on the port even though the stream is deleted, the old stream is still being transmitted.  

One way to get around with this is to call deleteStream, and then call modifyStream with a blank stream config.

With GUI, deleting stream is cleaning up correctly after clicking on the apply button.

Here is the test code:
(This is not cleaning properly)
tx_port  = ost_pb.PortIdList()
tx_port.port_id.add().id = 0
stream_id = ost_pb.StreamIdList()
stream_id.port_id.CopyFrom(tx_port.port_id[0])
stream_id.stream_id.add().id = 1
drone.addStream(stream_id)
drone.deleteStream(stream_id)

This seems to clean up properly:
drone.addStream(stream_id)
drone.deleteStream(stream_id)
stream_cfg = ost_pb.StreamConfigList() 
stream_cfg.port_id.id = 0
drone.modifyStream(stream_cfg)

**Comment by rfelten** [comment]
Stumbled on this issue in 0.8.0 too but I am happy to find a workaround here :)

**Comment by pstavirs** [comment]
This should have been fixed with addition of the `DroneProxy.build()` API and related changes in v1.0

Please reopen if issue is still seen in 1.0 or later.
