### ISSUE TITLE
Different user interface in streams and device groups for entering MAC addresses

### ISSUE THREAD

**Issue by ehlers** [pstavirs/ostinato#188]
In the streams and the device group UI the MAC addresses are entered slightly differently. In the streams UI the MAC addresses are shown (and entered) without the ":", in the device group UI the MAC addresses needs a separator (":" or "-").

I suggest to use the same input method in both cases.

**Comment by pstavirs** [comment]
Makes Sense

btw thanks for all the testing and bug reporting!

**Comment by pstavirs** [comment]
I've tagged this with the label `easy-fix`. This label is intended for people who are looking to contribute their first patches to the project
