### ISSUE TITLE
Add Resolve/Clear Neighbors buttons to the device information window

### ISSUE THREAD

**Issue by ehlers** [pstavirs/ostinato#189]
After setting up a device group the functions to start ARP/ND resolution are in the lower part of the GUI and the window to display the result are in the upper part. Furthermore you have to select the correct interface in the lower part of the GUI before doing the address resolution.

What about adding the "Resolve Neighbors" and "Clear Neighbors" buttons also in the device information window (next to the refresh button)? That way testing a newly created device group can be done completely in this window.

The buttons should also stay in the lower part to be able to easily initiate a new address resolution before starting a test.

**Comment by pstavirs** [comment]
This should be fairly straight foward to implement -

 * Use Qt Designer to add the "Resolve Neighbors" and "Clear Neighbors" buttons to the `client\deviceswidget.ui` on the information tab

 * Add private slots - `on_resolveNeighbors_clicked()` and `on_clearNeighbors_clicked()` to the `DevicesWidget` class

 * Model the code for the above new slots similar to the existing `on_refresh_clicked()` - and replace the call to  `PortGroup::getDeviceInfo()` with `PortGroup::resolveDeviceNeighbors()`and `PortGroup::clearDeviceNeighbors()` respectively
