### ISSUE TITLE
ports not found

### ISSUE THREAD

**Issue by little-dude** [pstavirs/ostinato#190]
Hi,

I'm running ostinato 0.7.1 in a very specific environment: an alpine linux with a custom kernel, running in a kvm vm. I know, that's asking for trouble, and I am actually having issues, because drone only returns the "any" port when fetching the ports through the python client.

Here are the drone logs:

```
Unable to load library icui18n "Cannot load library icui18n: (Error loading shared library icui18n: No such file or directory)"
Retrieving the device list from the local machine

0. any
 (Pseudo-device that captures on all interfaces)

cap file = /tmp/qt_temp.Ql1311
adding dev to all ports list <any>
1. nflog
 (Linux netfilter log (NFLOG) interface)

Error setting direction(0) nflog: Setting direction is not implemented on this platform

PortMonitor: Error opening port nflog: nflog: Can't listen on group group index: Operation not permitted

PortTransmitter: Error opening port nflog: nflog: Can't listen on group group index: Operation not permitted

cap file = /tmp/qt_temp.gB1311
adding dev to all ports list <nflog>
PortManager: unable to open nflog. Skipping!
In ~LinuxPort
In ~PcapPort
1. nfqueue
 (Linux netfilter queue (NFQUEUE) interface)

PortMonitor: Error opening port nfqueue: nfqueue: NFQNL_CFG_CMD_PF_UNBIND: Invalid argument

PortMonitor: Error opening port nfqueue: nfqueue: NFQNL_CFG_CMD_PF_UNBIND: Invalid argument

PortTransmitter: Error opening port nfqueue: nfqueue: NFQNL_CFG_CMD_PF_UNBIND: Invalid argument

cap file = /tmp/qt_temp.Pb1311
adding dev to all ports list <nfqueue>
PortManager: unable to open nfqueue. Skipping!
In ~LinuxPort
In ~PcapPort
nlmsg_flags = 301
netlink required buffer size = 3728
buffer size 3728 enough for netlink
if: lo(1)
if: bond0(2)
if: eth0(3)
buffer size 3728 enough for netlink
if: eth1(4)
if: eth2(5)
if: eth3(6)
buffer size 3728 enough for netlink
if: eth4(7)
if: eth5(8)
if: eth6(9)
buffer size 3728 enough for netlink
if: eth7(10)
if: eth8(11)
if: eth9(12)
buffer size 3728 enough for netlink
if: eth10(13)
if: sit0(14)
buffer size 3728 enough for netlink
port count = 0

no ports in RTNETLINK GET_LINK - no stats will be available
netlink stats not available - using /proc stats
stats for 14 ports setup
ComboProtocol: protoNumber = 208, 0x56399ea8ab60 <--> 0x56399ea8ac60
ComboProtocol: protoNumber = 206, 0x56399ea8b7a0 <--> 0x56399ea8b8a0
ComboProtocol: protoNumber = 206, 0x56399ea8bfa0 <--> 0x56399ea8c0a0
ComboProtocol: protoNumber = 207, 0x56399ea8bec0 <--> 0x56399ea8c1a0
ComboProtocol: protoNumber = 305, 0x56399ea8cdc0 <--> 0x56399ea8cf00
ComboProtocol: protoNumber = 304, 0x56399ea8d360 <--> 0x56399ea8d4a0
ComboProtocol: protoNumber = 303, 0x56399ea8d880 <--> 0x56399ea8d9c0
ComboProtocol: protoNumber = 306, 0x56399ea8dda0 <--> 0x56399ea8dee0
The server is running on 0.0.0.0: 7878
Version: 0.7.1
Revision: da551b378f72@
clientSock Thread = 0x56399ea943e0
[10.31.60.81:54993] accepting new connection from 10.31.60.81: 54993
[10.31.60.81:54993] Server(on_clientSock_dataAvail): successfully received/parsed msg <----
[10.31.60.81:54993] method = 15
[10.31.60.81:54993] req =
[10.31.60.81:54993] version: "0.7.1"
[10.31.60.81:54993] client_name: "python-ostinato"
[10.31.60.81:54993] ---->
[10.31.60.81:54993] In virtual void MyService::checkVersion(google::protobuf::RpcController*, const OstProto::VersionInfo*, OstProto::VersionCompatibility*, google::protobuf::Closure*)
[10.31.60.81:54993] client = 0.7.1, my = 0.7.1
[10.31.60.81:54993] Server(sendRpcReply): sending 10 bytes to client <----
[10.31.60.81:54993] 0002000f00000002
[10.31.60.81:54993] method = 15
[10.31.60.81:54993] req =
[10.31.60.81:54993] result: kCompatible
[10.31.60.81:54993] ---->
[10.31.60.81:54993] Server(on_clientSock_dataAvail): successfully received/parsed msg <----
[10.31.60.81:54993] method = 0
[10.31.60.81:54993] req =
[10.31.60.81:54993] ---->
[10.31.60.81:54993] In virtual void MyService::getPortIdList(google::protobuf::RpcController*, const OstProto::Void*, OstProto::PortIdList*, google::protobuf::Closure*)
[10.31.60.81:54993] Server(sendRpcReply): sending 12 bytes to client <----
[10.31.60.81:54993] 0002000000000004
[10.31.60.81:54993] method = 0
[10.31.60.81:54993] req =
[10.31.60.81:54993] port_id {
[10.31.60.81:54993]   id: 0
[10.31.60.81:54993] }
[10.31.60.81:54993] ---->
[10.31.60.81:54993] Server(on_clientSock_dataAvail): successfully received/parsed msg <----
[10.31.60.81:54993] method = 1
[10.31.60.81:54993] req =
[10.31.60.81:54993] port_id {
[10.31.60.81:54993]   id: 0
[10.31.60.81:54993] }
[10.31.60.81:54993] ---->
[10.31.60.81:54993] In virtual void MyService::getPortConfig(google::protobuf::RpcController*, const OstProto::PortIdList*, OstProto::PortConfigList*, google::protobuf::Closure*)
[10.31.60.81:54993] Server(sendRpcReply): sending 70 bytes to client <----
[10.31.60.81:54993] 000200010000003e
[10.31.60.81:54993] method = 1
[10.31.60.81:54993] req =
[10.31.60.81:54993] port {
[10.31.60.81:54993]   port_id {
[10.31.60.81:54993]     id: 0
[10.31.60.81:54993]   }
[10.31.60.81:54993]   name: "any"
[10.31.60.81:54993]   description: "Pseudo-device that captures on all interfaces"
[10.31.60.81:54993]   is_enabled: true
[10.31.60.81:54993]   is_exclusive_control: false
[10.31.60.81:54993] }
[10.31.60.81:54993] ---->

```

Do you know what I might be missing ?

**Comment by little-dude** [comment]
maybe it's because I'm missing libnetfilter_queue and libnetfilter_log?

**Comment by pstavirs** [comment]
Sounds like you are not running with admin/capture privileges. If that is
not the case, check if Wireshark or tcpdump see all the ports - Ostinato
uses the same PCAP API as Wireshark and tcpdump to discover the list of
ports

Srivats

On Thu, Jun 9, 2016 at 8:29 PM, little-dude <notifications@github.com>
wrote:

> Hi,
>
> I'm running ostinato 0.7.1 in a very specific environment: an alpine linux
> with a custom kernel, running in a kvm vm. I know, that's asking for
> trouble, and I am actually have issues, because drone only returns the
> "any" when fetching the ports through the python client.
>
> Here are the drone logs:
>
> Unable to load library icui18n "Cannot load library icui18n: (Error loading shared library icui18n: No such file or directory)"
> Retrieving the device list from the local machine
>
> 0. any
>  (Pseudo-device that captures on all interfaces)
>
> cap file = /tmp/qt_temp.Ql1311
> adding dev to all ports list <any>
> 1. nflog
>  (Linux netfilter log (NFLOG) interface)
>
> Error setting direction(0) nflog: Setting direction is not implemented on this platform
>
> PortMonitor: Error opening port nflog: nflog: Can't listen on group group index: Operation not permitted
>
> PortTransmitter: Error opening port nflog: nflog: Can't listen on group group index: Operation not permitted
>
> cap file = /tmp/qt_temp.gB1311
> adding dev to all ports list <nflog>
> PortManager: unable to open nflog. Skipping!
> In ~LinuxPort
> In ~PcapPort
> 1. nfqueue
>  (Linux netfilter queue (NFQUEUE) interface)
>
> PortMonitor: Error opening port nfqueue: nfqueue: NFQNL_CFG_CMD_PF_UNBIND: Invalid argument
>
> PortMonitor: Error opening port nfqueue: nfqueue: NFQNL_CFG_CMD_PF_UNBIND: Invalid argument
>
> PortTransmitter: Error opening port nfqueue: nfqueue: NFQNL_CFG_CMD_PF_UNBIND: Invalid argument
>
> cap file = /tmp/qt_temp.Pb1311
> adding dev to all ports list <nfqueue>
> PortManager: unable to open nfqueue. Skipping!
> In ~LinuxPort
> In ~PcapPort
> nlmsg_flags = 301
> netlink required buffer size = 3728
> buffer size 3728 enough for netlink
> if: lo(1)
> if: bond0(2)
> if: eth0(3)
> buffer size 3728 enough for netlink
> if: eth1(4)
> if: eth2(5)
> if: eth3(6)
> buffer size 3728 enough for netlink
> if: eth4(7)
> if: eth5(8)
> if: eth6(9)
> buffer size 3728 enough for netlink
> if: eth7(10)
> if: eth8(11)
> if: eth9(12)
> buffer size 3728 enough for netlink
> if: eth10(13)
> if: sit0(14)
> buffer size 3728 enough for netlink
> port count = 0
>
> no ports in RTNETLINK GET_LINK - no stats will be available
> netlink stats not available - using /proc stats
> stats for 14 ports setup
> ComboProtocol: protoNumber = 208, 0x56399ea8ab60 <--> 0x56399ea8ac60
> ComboProtocol: protoNumber = 206, 0x56399ea8b7a0 <--> 0x56399ea8b8a0
> ComboProtocol: protoNumber = 206, 0x56399ea8bfa0 <--> 0x56399ea8c0a0
> ComboProtocol: protoNumber = 207, 0x56399ea8bec0 <--> 0x56399ea8c1a0
> ComboProtocol: protoNumber = 305, 0x56399ea8cdc0 <--> 0x56399ea8cf00
> ComboProtocol: protoNumber = 304, 0x56399ea8d360 <--> 0x56399ea8d4a0
> ComboProtocol: protoNumber = 303, 0x56399ea8d880 <--> 0x56399ea8d9c0
> ComboProtocol: protoNumber = 306, 0x56399ea8dda0 <--> 0x56399ea8dee0
> The server is running on 0.0.0.0: 7878
> Version: 0.7.1
> Revision: da551b378f72@
> clientSock Thread = 0x56399ea943e0
> [10.31.60.81:54993] accepting new connection from 10.31.60.81: 54993
> [10.31.60.81:54993] Server(on_clientSock_dataAvail): successfully received/parsed msg <----
> [10.31.60.81:54993] method = 15
> [10.31.60.81:54993] req =
> [10.31.60.81:54993] version: "0.7.1"
> [10.31.60.81:54993] client_name: "python-ostinato"
> [10.31.60.81:54993] ---->
> [10.31.60.81:54993] In virtual void MyService::checkVersion(google::protobuf::RpcController*, const OstProto::VersionInfo*, OstProto::VersionCompatibility*, google::protobuf::Closure*)
> [10.31.60.81:54993] client = 0.7.1, my = 0.7.1
> [10.31.60.81:54993] Server(sendRpcReply): sending 10 bytes to client <----
> [10.31.60.81:54993] 0002000f00000002
> [10.31.60.81:54993] method = 15
> [10.31.60.81:54993] req =
> [10.31.60.81:54993] result: kCompatible
> [10.31.60.81:54993] ---->
> [10.31.60.81:54993] Server(on_clientSock_dataAvail): successfully received/parsed msg <----
> [10.31.60.81:54993] method = 0
> [10.31.60.81:54993] req =
> [10.31.60.81:54993] ---->
> [10.31.60.81:54993] In virtual void MyService::getPortIdList(google::protobuf::RpcController*, const OstProto::Void*, OstProto::PortIdList*, google::protobuf::Closure*)
> [10.31.60.81:54993] Server(sendRpcReply): sending 12 bytes to client <----
> [10.31.60.81:54993] 0002000000000004
> [10.31.60.81:54993] method = 0
> [10.31.60.81:54993] req =
> [10.31.60.81:54993] port_id {
> [10.31.60.81:54993]   id: 0
> [10.31.60.81:54993] }
> [10.31.60.81:54993] ---->
> [10.31.60.81:54993] Server(on_clientSock_dataAvail): successfully received/parsed msg <----
> [10.31.60.81:54993] method = 1
> [10.31.60.81:54993] req =
> [10.31.60.81:54993] port_id {
> [10.31.60.81:54993]   id: 0
> [10.31.60.81:54993] }
> [10.31.60.81:54993] ---->
> [10.31.60.81:54993] In virtual void MyService::getPortConfig(google::protobuf::RpcController*, const OstProto::PortIdList*, OstProto::PortConfigList*, google::protobuf::Closure*)
> [10.31.60.81:54993] Server(sendRpcReply): sending 70 bytes to client <----
> [10.31.60.81:54993] 000200010000003e
> [10.31.60.81:54993] method = 1
> [10.31.60.81:54993] req =
> [10.31.60.81:54993] port {
> [10.31.60.81:54993]   port_id {
> [10.31.60.81:54993]     id: 0
> [10.31.60.81:54993]   }
> [10.31.60.81:54993]   name: "any"
> [10.31.60.81:54993]   description: "Pseudo-device that captures on all interfaces"
> [10.31.60.81:54993]   is_enabled: true
> [10.31.60.81:54993]   is_exclusive_control: false
> [10.31.60.81:54993] }
> [10.31.60.81:54993] ---->
>
>
> Do you know what I might be missing ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pstavirs/ostinato/issues/190>, or mute the thread
> <https://github.com/notifications/unsubscribe/AIAZRxnm2sTltJPNFj1JKqA94v4C8uw3ks5qKCo9gaJpZM4IyEUl>
> .
>



-- 
http://ostinato.org/
@ostinato

**Comment by little-dude** [comment]
I'm running ostinato as root actually. And tcpdump seems to be able to capture on all the interfaces.

**Comment by pstavirs** [comment]
1. What is the output of "tcpdump -D"?
2. Use ldd to confirm that both tcpdump and drone are using the same pcap
library at run time

On Thu, Jun 9, 2016 at 8:45 PM, little-dude <notifications@github.com>
wrote:

> I'm running ostinato as root actually. And tcpdump seems to be able to
> capture on all the interfaces.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pstavirs/ostinato/issues/190#issuecomment-224927622>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIAZRzXvphJDOjNM4CgeInV2unq5OhNLks5qKC4KgaJpZM4IyEUl>
> .
>



-- 
http://ostinato.org/
@ostinato

**Comment by little-dude** [comment]
```alpine:~# tcpdump -D
1.eth0 [Up, Running]
2.eth1 [Up, Running]
3.eth2 [Up, Running]
4.any (Pseudo-device that captures on all interfaces) [Up, Running]
5.lo [Up, Running, Loopback]
6.nflog (Linux netfilter log (NFLOG) interface)
7.nfqueue (Linux netfilter queue (NFQUEUE) interface)

alpine:~# ldd $(which tcpdump)
        /lib/ld-musl-x86_64.so.1 (0x560c2ec86000)
        libcrypto.so.1.0.0 => /lib/libcrypto.so.1.0.0 (0x7f57c7d27000)
        libpcap.so.1 => /usr/lib/libpcap.so.1 (0x7f57c7aec000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x560c2ec86000)
        libz.so.1 => /lib/libz.so.1 (0x7f57c78d6000)

alpine:~# ldd $(which drone)
        /lib/ld-musl-x86_64.so.1 (0x5595d92de000)
        libpcap.so.1 => /usr/lib/libpcap.so.1 (0x7fdf7a17f000)
        libprotobuf.so.9 => /usr/lib/libprotobuf.so.9 (0x7fdf79e84000)
        libQtScript.so.4 => /usr/lib/libQtScript.so.4 (0x7fdf799c8000)
        libQtNetwork.so.4 => /usr/lib/libQtNetwork.so.4 (0x7fdf79679000)
        libQtCore.so.4 => /usr/lib/libQtCore.so.4 (0x7fdf79184000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fdf78e34000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fdf78c21000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x5595d92de000)
        libz.so.1 => /lib/libz.so.1 (0x7fdf78a0b000)
        libssl.so.1.0.0 => /lib/libssl.so.1.0.0 (0x7fdf787a3000)
        libcrypto.so.1.0.0 => /lib/libcrypto.so.1.0.0 (0x7fdf78386000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x7fdf7809a000)
        libpcre.so.1 => /usr/lib/libpcre.so.1 (0x7fdf77e41000)
        libintl.so.8 => /usr/lib/libintl.so.8 (0x7fdf77c33000)
```

looks like they use the same

**Comment by little-dude** [comment]
@pstavirs am I hitting this bug? I don't really understand it: https://www.wireshark.org/lists/wireshark-bugs/201501/msg00554.html

**Comment by pstavirs** [comment]
I am stumped. Can't think of anything except to say that double check that
you are indeed running Drone as root.

On Thu, Jun 9, 2016 at 8:59 PM, little-dude <notifications@github.com>
wrote:

> ```alpine:~# tcpdump -D
> 1.eth0 [Up, Running]
> 2.eth1 [Up, Running]
> 3.eth2 [Up, Running]
> 4.any (Pseudo-device that captures on all interfaces) [Up, Running]
> 5.lo [Up, Running, Loopback]
> 6.nflog (Linux netfilter log (NFLOG) interface)
> 7.nfqueue (Linux netfilter queue (NFQUEUE) interface)
>
> alpine:~# ldd $(which tcpdump)
> /lib/ld-musl-x86_64.so.1 (0x560c2ec86000)
> libcrypto.so.1.0.0 => /lib/libcrypto.so.1.0.0 (0x7f57c7d27000)
> libpcap.so.1 => /usr/lib/libpcap.so.1 (0x7f57c7aec000)
> libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x560c2ec86000)
> libz.so.1 => /lib/libz.so.1 (0x7f57c78d6000)
>
> alpine:~# ldd $(which drone)
> /lib/ld-musl-x86_64.so.1 (0x5595d92de000)
> libpcap.so.1 => /usr/lib/libpcap.so.1 (0x7fdf7a17f000)
> libprotobuf.so.9 => /usr/lib/libprotobuf.so.9 (0x7fdf79e84000)
> libQtScript.so.4 => /usr/lib/libQtScript.so.4 (0x7fdf799c8000)
> libQtNetwork.so.4 => /usr/lib/libQtNetwork.so.4 (0x7fdf79679000)
> libQtCore.so.4 => /usr/lib/libQtCore.so.4 (0x7fdf79184000)
> libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fdf78e34000)
> libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fdf78c21000)
> libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x5595d92de000)
> libz.so.1 => /lib/libz.so.1 (0x7fdf78a0b000)
> libssl.so.1.0.0 => /lib/libssl.so.1.0.0 (0x7fdf787a3000)
> libcrypto.so.1.0.0 => /lib/libcrypto.so.1.0.0 (0x7fdf78386000)
> libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x7fdf7809a000)
> libpcre.so.1 => /usr/lib/libpcre.so.1 (0x7fdf77e41000)
> libintl.so.8 => /usr/lib/libintl.so.8 (0x7fdf77c33000)
>
>
> looks like they use the same
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pstavirs/ostinato/issues/190#issuecomment-224932249>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIAZR4kOoqRxmDd4YYoFR4I53jFldyP3ks5qKDFogaJpZM4IyEUl>
> .
>



-- 
http://ostinato.org/
@ostinato

**Comment by little-dude** [comment]
> double check that you are indeed running Drone as root
I am, there is not other user =/

**Comment by little-dude** [comment]
```alpine:~# dumpcap -D
1. eth0
2. any
3. lo (Loopback)
4. nflog
5. nfqueue
```

**Comment by little-dude** [comment]
Oops... I'm *really* sorry, it's all my fault. I'm starting drone at start up as a daemon... and I just noticed it was started before the networking:
```
 * Starting drone ... [ ok ]                  
 * Setting hostname ... [ ok ]                
 * Starting networking ... *   lo ... [ ok ]  
```
Sorry about this... I just tested, it does work when I start it after the networking service...
