### ISSUE TITLE
Support protobuf release 3.x

### ISSUE THREAD

**Issue by pstavirs** [pstavirs/ostinato#193]
From #167 -

@sshamray wrote :
> ... while I try to make then I receive error message:

>`/home/user/Documents/ostinato/ostinato_1/rpc/rpcconn.cpp:380: error: 'NewCallback' is not a member of 'google::protobuf'`
> `google::protobuf::NewCallback(this, &RpcConnection::sendRpcReply,`

@sebastic  wrote
>Debian is migrating to protobuf 3.x and the ostinato package failed to build due to this issue as reported in Debian Bug #835435.

>Please consider re-opening this issue and supporting protobuf 3.x.

@kartikm wrote -
>As @sebastic mentioned. Otherwise, package need to removed from Debian :/

This is about fixing the build issue with protobuf release 3.x, not about supporting or upgrading to proto3   language syntax. Protobuf release 3.x supports both proto2 and proto3 language syntaxes

**Comment by pstavirs** [comment]
Upon investigation, this is a problem not with Ostinato but with Protobuf. `NewCallback` was moved from `google::protobuf` to `google::protobuf::internal` namespace incorrectly and needs to be moved back

See google/protobuf#1966

We could change the Ostinato source code to use the new namespace but the build will break again when protobuf fixes the issue.

@sebastic @kartikm: Any suggestions on how do we solve this on Debian? Can we fix this in the Debian protobuf package till protobuf upstream fixes the same?

**Comment by sebastic** [comment]
Patching the protobuf package in Debian is an option, is a patch already available? The issue in the google/protobuf tracker does not show any progress nor feedback.

**Comment by pstavirs** [comment]
I'm trying to come up with a patch

**Comment by pstavirs** [comment]
I've submitted PR google/protobuf#2024 to fix this in protobuf

**Comment by sebastic** [comment]
I've turned the changes from https://github.com/google/protobuf/pull/2024 into a patch for the protobuf Debian package, and submitted it to the protobuf maintainers in [Debian Bug #836200](http://bugs.debian.org/836200).

The patch for protobuf has been confirmed to fix the ostinato build failure with protobuf 3.0.0.

**Comment by kartikm** [comment]
@pstavirs Thanks a lot!

**Comment by sebastic** [comment]
I guess this issue can be closed now that protobuf includes the fix.

**Comment by kartikm** [comment]
Yes. This can be close. Thanks!

**Comment by pstavirs** [comment]
@sebastic @kartikm : Thanks for taking care from the Debian side. I'm closing this issue now

**Comment by sebastic** [comment]
I've pushed some changes to fix the syntax warnings with protobuf 3.0.0 in #194, I figured that should really resolve this issue.
