### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by jgroom33** [pstavirs/ostinato#198]
It is only my gratitude and admiration of this package that allows me to submit this issue.

I would love to see Ostinato as an electron app:
http://electron.atom.io/

Make networking great again!

**Comment by jgroom33** [comment]
Here are the others that are moving that direction:
[packet capture](https://dripcap.org/)
[hyperterminal](https://hyper.is/)

**Comment by pstavirs** [comment]
It was only a few weeks ago that I first heard about Electron on the [ChangeLog](http://changelog.com) podcast and thought to myself that it'd be cool to have Ostinato as an electron app.

However, realistically speaking, with my limited time (and limited knowledge of web technologies), I don't think it is feasible for me personally to do both the Qt GUI and Electron UI. It might still be a good experiment to have an Electron App for a specific use case and workflow of using Ostinato/Drone - if someone makes the case for it.

@jgroom33 could you articulate your reasons or use case where you think Electron would be better suited than what we have today with Qt?

Alternatively, if someone else wants to build and maintain an Electron App, I can help with consultation et. al.

**Comment by pstavirs** [comment]
No plans to have an Electron GUI
