### ISSUE TITLE
Protobuf 3.0.0 build error

### ISSUE THREAD

**Issue by ejb1123** [pstavirs/ostinato#199]
I am working on getting protobuf in the FreeBSD ports tree to version v3.0.0 from v2.6.1. The current version of otinato in the ports tree is 0.8. Would it be possible to make ostinato compatible with protobuf 3.0.0?
[Here is a build log](https://gist.github.com/ejb1123/bc68eb4940beb35f1bcd385bc47d1131)

**Comment by pstavirs** [comment]
The build error is because of a protobuf problem that is fixed in protobuf v3.1.0 - see #193
