### ISSUE TITLE
Building drone server without QT dependency.

### ISSUE THREAD

**Issue by ndprasad09** [pstavirs/ostinato#200]
Hi,
I want to run drone server on embedded device which is headless and also does not run any Xserver. So I build ostinato drone server alone without any QT library dependency. Is this possible because currently now the build process is 
qmake - 
make
make install.

When I run qmake I get below error
"could not exec /usr/lib/x86_64/qt4/bin/qmake".
Is there something like make drone which compile drone server alone?

**Comment by pstavirs** [comment]
To build drone only, you can use -
```
$ qmake
$ make server
````
but you still need some Qt libraries - not the GUI ones though.

The best advice I can give you is to find a way to build the required Qt libraries for your embedded platform - it is doable and supported (for help talk to the Qt folks - we won't be able to help you)

See #96 for some history
