### ISSUE TITLE
auto stop capture

### ISSUE THREAD

**Issue by jungle-boogie** [pstavirs/ostinato#204]
Hello,

Thanks for ostinato and maintaining it for 7 (?) years now!

I would like to add a feature request to automatically stop the packet capture once all packets and streams are completed.

Alternatively, perhaps something within the streams to stop the capture. 

Thanks,
j.b.

**Comment by pstavirs** [comment]
@jungle-boogie Could you describe your use case? If port A is sending to port B, and you are capturing on port B, how does it come to know that port A has finished transmission?

**Comment by jungle-boogie** [comment]
Hi @pstavirs,

Start ostinato on a machine with a single nic and setup a stream. When you start the transmission, the status changes from `off` to `on`, but before starting the transmission, you will need start the capture and then the transmission. Once the transmission is over, the status will change from `on` to `off`, but capturing will still happen.

Can the start capture monitor the on/off status of the transmission?

**Comment by pstavirs** [comment]
@jungle-boogie What is your use case? Why are you capturing the transmitted packets? How will this feature work for the destination port which is not transmitting?

**Comment by jungle-boogie** [comment]
Hi @pstavirs,

Use case is to start ostinato on a machine with a single nic and setup a stream and then you start transmitting, but won't a capture also pickup non-ostinato traffic? If auto stop capture were implemented, you wouldn't need to watch for the change from on to off on the transmission to know when you can stop the capture. 

What's your use case where you don't mind watching the transmission state changing from off to on back to off to then stop the capture?

**Comment by pstavirs** [comment]
@jungle-boogie What about my other questions?

**Comment by jungle-boogie** [comment]
> How will this feature work for the destination port which is not transmitting?

no idea.

**Comment by pstavirs** [comment]
Use case and requirements/specifications for this feature are not clear. Closing for now.

**Comment by jungle-boogie** [comment]
Hi @pstavirs,

Can you please explain how you capture traffic generated by Ostinato and only Ostinato to later review in wireshark if you have only a single NIC?
