### ISSUE TITLE
update gawk on MS Windows builds

### ISSUE THREAD

**Issue by jungle-boogie** [pstavirs/ostinato#205]
Hello,

This is a request to update GNU awk to latest version.
Currently installed `GNU Awk 3.1.0`

Currently available:
4.14
https://sourceforge.net/projects/ezwinports/files

Thanks!

**Comment by pstavirs** [comment]
@jungle-boogie why do you need the latest awk version as part of Ostinato?

**Comment by jungle-boogie** [comment]
hi @pstavirs, just pointing out the one you're supplying in ostinato is quite old. New software not only brings features but optimizations and bug fixes.

**Comment by pstavirs** [comment]
@jungle-boogie awk is used only for the case of doing a diff in the "intelligent" import via PDML of PCAP files in Ostinato - so will keep this low priority

**Comment by pstavirs** [comment]
On second-thoughts, low priority items never get done. Will close for now. If the version of awk is creating a "problem", will reopen and upgrade.
