### ISSUE TITLE
Python unable to using native binary ostm format files.

### ISSUE THREAD

**Issue by Mike-A-H** [pstavirs/ostinato#206]
Attempting to read ostm file in Python using the following:

```
fileMsg = ostinato.protocols.fileformat_pb2.File()

f = open("test.ostm", "rb")
fileMsg.ParseFromString(f.read())
f.close()
```
magic_value, meta_data, and checksum_value are read correctly.

fileMsg.content_matter.streams does not contain any data.  fileMsgcontent_matter._unknown_fields does have a single tuple in the list.  This tuple appears to have the data, but it must not be parsed correctly.

Originally reported via mailing list - https://groups.google.com/d/topic/ostinato/RHDT4IKh3x4/discussion

**Comment by pstavirs** [comment]
Fixed via 81bb5f5
