### ISSUE TITLE
Minor Edit Stream UI issues

### ISSUE THREAD

**Issue by malvidin** [pstavirs/ostinato#207]
Misspelling of destination
/common/mac.cpp
line 146

Packet View's hex dump excludes printable characters
/client/dumpview.h
line 51
Recommend including spaces (32, 0x20) to tilde (126, 0x7E), instead of 1 (49, 0x31) to } (125, 0x7D):
        {if ((c >= 32 ) && (c <= 126)) return true; else return false; }

This matches the Hex Dump payload view, which displays all characters between 0x20 and 0x7D, inclusive.

**Comment by pstavirs** [comment]
Thanks for reporting the issues @malvidin - would you like to take a stab at submitting a patch or pull request?

**Comment by pstavirs** [comment]
Thank you for the pull request @malvidin!
