### ISSUE TITLE
Ostinato crashes, when opening pcap stream containing STP packets

### ISSUE THREAD

**Issue by ehlers** [pstavirs/ostinato#213]
Ostinato V0.8, tested on Debian 9 (Stretch) and TinyCore Linux, tshark v2.2.5

When opening a pcap stream ostinato crashes with segmentation fault.

Here the log of ostinato and the pcap file [crash.zip](https://github.com/pstavirs/ostinato/files/908085/crash.zip)

**Comment by ehlers** [comment]
Ostinato doesn't crash on all pcap files, only on some special ones. I assume it's the spanning tree BPDU that irritates Ostinato.

**Comment by pstavirs** [comment]
@ehlers Thanks for reporting the issue and with a PCAP file showing the problem which made it easy to repro and debug.

The problem will happen only when the PCAP contains a STP protocol packet.

**Comment by pstavirs** [comment]
Fixed by 8b2541f
