### ISSUE TITLE
inter stream gap

### ISSUE THREAD

**Issue by ashishkurian** [pstavirs/ostinato#216]
Dear Folks,

I am opening up this issue to request to add a new feature of inter stream gap. There is no option to have a wait between two streams. For example in the case of Vehicle-to-Vehicle (V2V) traffic, after the first packet of 300 bytes, there should be a gap of 100 milliseconds before sending the subsequent packets of 190 bytes. If we create two different stream for these two packets, after the 300 byte, it will immediately send the 190 byte packet without waiting.

**Comment by pstavirs** [comment]
This should work - setting the first stream packets/sec rate to 10 (1000ms/100ms) should do the trick -

![image](https://github.com/pstavirs/ostinato/assets/8395079/351861a8-5953-4efa-a1e5-300cb9536b4d)
