### ISSUE TITLE
distribution based triggering of a stream

### ISSUE THREAD

**Issue by ashishkurian** [pstavirs/ostinato#217]
Dear Folks,

Another interesting feature to have would be have a trigger for a stream based on a particular distribution. For example, let us say that we have a set of streams that are ordered to be generated sequentially. It would be sometimes required to have another stream which is of critical importance to be generated based on Poisson distribution with a specific Poisson rate. This stream should interrupt all other streams and send its packets. After the priority stream is done, we should resume the old sequential streams.

**Comment by pstavirs** [comment]
As explained in the [associated email thread](https://groups.google.com/d/topic/ostinato/xFrB1gTHabU/discussion), this should be done in user code using the Python API.
