### ISSUE TITLE
Newbit and Sample OSSN scripts to simulate a real company network

### ISSUE THREAD

**Issue by John8456** [pstavirs/ostinato#220]
I have some Ethernet hardware and although it works here in my small office, it is crashing at medium size company sites.

I would like to generate "general" office IP noise and traffic. Like multicasts, VoiP, UDP and a wide group or "other" traffic etc Does anyone have links to ready-to-go script(s) that can generate generic, mixed and noisy traffic so I can try to see if my product is somehow crashing in a noisy environment.

i.e. Has anyone build a few versions like "general o" and "crazy busy 25MB"

THANKS TO ALL in advance.
John

**Comment by pstavirs** [comment]
There are more eyes looking at the mailing list - ostinato at googlegroups dot com than here. So you'll have better luck if you posted there.
