### ISSUE TITLE
Opening captured stream gives wrong ip version and header.

### ISSUE THREAD

**Issue by karthikbhata97** [pstavirs/ostinato#221]
Steps to reproduce:
Open any captured pcap file in ostinato and read using pdml.
Then the ip version and header gives wrong values.

I think this is because, in ip4pdml.cpp, ip.version is taken as known field for ip.ver_header but in actual pdml data, ip.hdr_len holds value of version+header(1 byte).

**Comment by pstavirs** [comment]
Duplicate of #219
