### ISSUE TITLE
Make port names more descriptive on Windows

### ISSUE THREAD

**Issue by angelyouyou** [pstavirs/ostinato#222]
list in Ports and Streams can not show the Physical NetCard
especially when PC have more than one loopback interfaces (shown as  "MS Loopback Drivier"), can not distinguished between each other.

**Comment by pstavirs** [comment]
@angelyouyou you can't see any ports at all or you can see some but not all?

If you can't see any ports, check http://ostinato.org/docs/faq#q-port-group-has-no-interfaces

If you can't see some ports, check -
 * is the port administratively enabled?
 * can Wireshark capture on that port?

If you have two loopback ports you can distinguish them with the ifX name given to them

**Comment by angelyouyou** [comment]
@pstavirs
I have two  have two loopback ports, these ports are shown with "Port X:ifX MS Loopback Driver".
From the character 'X', I still not distinguish them.
In my opinion, you can show these ports name same with "ipconfig" command in "cmd.exe" on Windows platform.

**Comment by pstavirs** [comment]
@angelyouyou can you attach a screenshot of the Ostinato ports list window and output of `ipconfig /all` so that I can understand the problem better?

**Comment by angelyouyou** [comment]
![image](https://user-images.githubusercontent.com/12936259/32274355-6f97cc06-bf41-11e7-8580-fbb1c62a50f3.png)
![image](https://user-images.githubusercontent.com/12936259/32274365-7742886a-bf41-11e7-9ed8-e06968cb0334.png)

**Comment by pstavirs** [comment]
For reference: How [wireshark retrieves friendly interface names](https://github.com/wireshark/wireshark/blob/2832f4e97d77324b4e46aac40dae0ce898ae559d/caputils/capture_win_ifnames.c#L231)
