### ISSUE TITLE
editable label/field for port description in the Statistics view

### ISSUE THREAD

**Issue by burren-m** [pstavirs/ostinato#223]
Hi Srivats,

when using multiple ports in a network under test, I sometimes tend to loose track of what Ostinato port goes to which DUT port. Maybe in the course of the upcoming UX improvements, would it be possible to add an editable description or label field just under the Port Title in the Statistics view of the GUI? That would allow to add labels like 'R1, port 1/0/1'.  This could help to prevent human mistakes when executing manual tests.

Thanks a lot for considering =)
Martin

P.S:. could also be stored at drone? Labels would then also survive a GUI restart and be available to multiple controllers.

**Comment by ripnet** [comment]
Any chance of getting this? I use multiple drones, each with 8 ports, and the ability to add a description next to the Port name in the tree would be super beneficial.

**Comment by pstavirs** [comment]
@ripnet Your request is slightly different from @burren-m's - both are talking about associating a user defined description field, but Martin's request is for showing the description in the _Port Statistics_ window, while you would like to see it in the _Port Groups and Ports_ **tree**? Maybe we should add to both?

Should this description be entered using the GUI or is it enough to specify it manually in the `drone.ini` - the latter would make it survive reboots of the drone agent. But that also means any change in connectivity should be followed by change in the drone.ini also so as to not be misleading.

Thoughts?

**Comment by ripnet** [comment]
@pstavirs Hi. I would prefer using the GUI, as long as the descriptions can be saved in my session file. I frequently change the links (using GNS3) and having to edit an `ini` file and reboot would be cumbersome.

However, that said, I'd settle for anything. If the majority of users would prefer the `ini` setting, that's ok with me.

Thanks for your consideration.

**Comment by pstavirs** [comment]
@ripnet Unrelated to this feature, you mentioned that you use Ostinato with GNS3 and session files. Have some questions related to that -
* Do you access the Ostinato GUI via VNC on GNS3
* If so, your session files are stored in the Ostinato VM - how do you make them survive a reboot?

I've been thinking about improving the UX for Ostinato on GNS3 and other labbing platforms and wanted to understand the current usage patterns and any suggestions, if you have.

**Comment by pstavirs** [comment]
Commit 32ddf223b6a0ecd27ed3d8bd9d96f70f6b211aff adds the display of the description to the Port Stats Window as well. Above referenced Twitter thread includes the screenshot.

Marking this feature DONE!

**Comment by ripnet** [comment]
@pstavirs 

I use the Mac GUI client, and add the drones to my port groups list. I keep the session files on my mac (google drive).

I would like to see something to load my previous session easier. My suggestions: either automatically use the last saved session, or allow the GUI to be launched with the ossn file as a command line argument and it will load that. It's a minor thing, but adds a few minutes each time I start my test.

Thanks!

**Comment by pstavirs** [comment]
@ripnet You can pass the ossn file as a command line parameter to the GUI -
see  Command Line Options - Ostinato Guides
<https://userguide.ostinato.org/command-line/#ostinato>

I will think about auto-saving and restoring the last session.
