### ISSUE TITLE
crash for MAC Increment/Decrement count=0

### ISSUE THREAD

**Issue by burren-m** [pstavirs/ostinato#224]
Hi Srivats,

I just observed that for MAC Address modes Increment/Decrement, when the Count is set to 0, the GUI will crash (at least for Windows, Ostinato 0.7.1).

I was also wondering what might be the reason for limiting Increment/Decrement Count to 999? This requires L2 bridge CAM size testing to partition into multiple steps and changing MAC base address each 999 packets sent.

Thank you very much,
Martin

**Comment by pstavirs** [comment]
@burren-m : Thanks for reporting the issue! I will look at it.

btw the 999 is just a UI limitation that you can workaround by using Variable fields.

**Comment by pstavirs** [comment]
@burren-m The minimum value for count should be 1  as you would be sending at least one frame. Is there any specific behaviour you were looking for while configuring value 0 for count?

**Comment by burren-m** [comment]
@pstavirs : As we discussed earlier, I was looking for a way to go beyond the 999 increments allowed by the UI and since '0' sometimes is used as special value for infinite, etc, I gave it a try. So no real specific use case behind. And as you hinted in your previous reply, variable fields serve this purpose perfectly ;)

Btw talking of crashes, accidentally double clicking the magnifying glass icon for launching Wireshark will also crash the GUI, if the respective port in Ostinato is in Capture State = On (Ostinato 0.7.1 on Win). 

Cheers,
Martin

**Comment by burren-m** [comment]
@pstavirs : As we discussed earlier, I was looking for a way to go beyond the 999 increments allowed by the UI and since '0' sometimes is used as special value for infinite, etc, I gave it a try. So no real specific use case behind. And as you hinted in your previous reply, variable fields serve this purpose perfectly ;)

Btw talking of crashes, accidentally double clicking the magnifying glass icon for launching Wireshark will also crash the GUI, if the respective port in Ostinato is in Capture State = On (Ostinato 0.7.1 on Win).

Cheers,
Martin

**Comment by burren-m** [comment]
sorry, closed it accidentally...

**Comment by pstavirs** [comment]
> Btw talking of crashes, accidentally double clicking the magnifying glass icon for launching Wireshark will also crash the GUI, if the respective port in Ostinato is in Capture State = On (Ostinato 0.7.1 on Win).

I'm able to reproduce this with the released binary of 0.7.1 but if I build a new binary based on the 0.7.1 code to debug this issue, I'm not able to reproduce it with that. One difference is that I have upgraded Qt from 4.3.3 to 4.8.7. Maybe that could be a potential reason.

Since I'm not able to reproduce the crash with 0.8 or the latest code also, I plan to ignore this crash report. If you see this crash with the upcoming 0.9, please open a new issue
