### ISSUE TITLE
Variable Fields: Vlan Priority Increment does not work

### ISSUE THREAD

**Issue by burren-m** [pstavirs/ostinato#227]
Hi,

I was trying to increment through PCPs 0 to 7, using variable fields on the Vlan protocol header.  However, PCP sent will always be zero, the Variable Field entry created will always say 'Vlan Priority Increment from 0 to 0'. Same applies if I try to build this function using a Custom field instead of Priority field.
Using Ostinato 0.7.1 for Windows.

Can you confirm?

Cheers,
Martin

**Comment by pstavirs** [comment]
@burren-m Please attach a Ostinato stream here which exhibits the problem you describe

**Comment by pstavirs** [comment]
No update from submitter. Closing.
