### ISSUE TITLE
Strange behaviour for PortIdList for different VMs

### ISSUE THREAD

**Issue by JeevanNailwal** [pstavirs/ostinato#228]
I am trying to run on my 3 virtual machines.  All 3 virtual machines are snapshot of single VM image. In each of my VM, I have eth0 as my tap device to connect to my host machine, 2 eth ports.

Although I have common drone.ini for all my VMs in which:
{PortList]
Include=eth*
Exclude=eth0,any,lo

During my experiment, I am facing a strange behaviour in ostinato. In one of my machine, I am getting all my port in port-lists(eth0, eth1, eth2, lo, any) while in another machine, I am getting only eth1 and eth2 in my portIdlist.

Please find the attached logfile and let me know if I missed anything. please let me know if you need any more logs from my side.

[bad_startup_logs.txt](https://github.com/pstavirs/ostinato/files/1538048/bad_startup_logs.txt)
[gud_startup_logs.txt](https://github.com/pstavirs/ostinato/files/1538049/gud_startup_logs.txt)

**Comment by pstavirs** [comment]
I see this in the bad log -
```
Unable to start the server: The bound address is already in use
```
This indicates that there is another instance of drone already running on this VM. Please check.

**Comment by JeevanNailwal** [comment]
Hi Srivats,
The log which you mention is because of continuity of my logs. Sorry for
that.

My makor concern was the output of PortIdlist and PortConfig list: In one
of VM (when drone was running), I can see 2 ports(eth1 and eth2) which was
expected as rest all ports, i had added in excluded list of my ini file
while in another VM, even though my exclude list is same, I am geting al 5
ports in both ;lists.

Regards,
Jeevan Nailwal

PS: plz let me know if you need a fresh set of logs.

**Comment by JeevanNailwal** [comment]
Srivats was right, double instances of client were creating the issue. Althogh I am facing some more issues regarding drone, but I wil open seperate issue for that. Hence closing this one.

Once again, thanks for  your prompt replies.
