### ISSUE TITLE
crash in rpc via getStats - PeerClosedConnError and Truncated message

### ISSUE THREAD

**Issue by JeevanNailwal** [pstavirs/ostinato#232]
Hi all,
I am creating a ostinato setup.
I have 2 threads in my program
1. A 3 second timer thread to collect the stats after 3 second and send it to server to display.
2. A normal client-server thread, which waits on a socket to get the command from server(like transmit/ capture pcap).

In start, everything works normal. But as soon as I send transmit command to my client, I get the 2 different crashes
1.  in line 96 of rpc.py.(please find my logs+ rpc logs in attachment)   
[closed_Conn_error_de.txt](https://github.com/pstavirs/ostinato/files/1547214/closed_Conn_error_de.txt)
[closed_conn_error_screen.txt]

2. DecodeError: Truncated message in line 610 of decode.py

[truncate_error_de.txt](https://github.com/pstavirs/ostinato/files/1547216/truncate_error_de.txt)

Please find my pkt sender script below for your reference.(plz change .txt to .py)
[cdns_vb_pkt_sender_mod.txt](https://github.com/pstavirs/ostinato/files/1547234/cdns_vb_pkt_sender_mod.txt)

As per my analysis, I am using Drone(localhost) API to connect to running drone while sending pkt. It is creating some garbage values which is leading to system crash.

**Comment by JeevanNailwal** [comment]
Found another error 1.1. OverflowError: signed integer is greater than maximum along with Truncated message error.

I had tested rpc like start capture and stop capture( for capturing pcap data) send packets on different ports. They all are working fine. Except getStats,  since all the code has been written in try catch module. 

In my app, I am trying to get logs every 3 seconds via a independent thread. Once code breaks in getStats rpc, it is continuously failing in that segment and giving different logs.

Please have a look on the attached logs. It has both rpc logs and my logs combined. 
[logs_12dec.txt](https://github.com/pstavirs/ostinato/files/1550705/logs_12dec.txt)

**Comment by pstavirs** [comment]
The Ostinato Python API has not been tested with multi-threading and is most likely thread-unsafe.

Please use different processes.

**Comment by JeevanNailwal** [comment]
Hi srivats,
Can you please let me know, how to stop rpc and other debug messages on screen? Its so annoying and too much data for my logs, to analyze my issue.

**Comment by pstavirs** [comment]
@JeevanNailwal See https://apiguide.ostinato.org/faq.html
