### ISSUE TITLE
Stream statistics API missing in API documentation

### ISSUE THREAD

**Issue by ehlers** [pstavirs/ostinato#235]
Version 0.9

The stream statistics API is missing in the documentation https://apiguide.ostinato.org/

**Comment by pstavirs** [comment]
Documentation updated

**Comment by ehlers** [comment]
I saw quite a lot of new stream statistics related documentation in module core and ost_pb, very nice. But there is a reference to protocols / sign_pb with no content. Is there something missing?

**Comment by pstavirs** [comment]
@ehlers Missed committing a file. Fixed now. Thanks for pointing that out!
