### ISSUE TITLE
Feature request : A way to view traffic rate in bits/sec, kbits/sec, mbits/sec or gbits/sec & packets/sec  in the client application

### ISSUE THREAD

**Issue by jimitsalvi** [pstavirs/ostinato#241]
Would love to have a feature where we can toggle the port statistics view between bits/sec, kbits/sec, mbits/sec or gbits/sec in addition to packets/sec.

The reason is all the network devices show the traffic rate in either pps & kbps. which makes it easier for troubleshooting.

TenGigE0/0/0/27 is up, line protocol is up
Encapsulation ARPA

Traffic Stats:(2 second rates)                                     Delta
  Input  Packets:                       145                            2
  Input  pps:                             0
  Input  Bytes:                       83960                         1180
  Input  Kbps (rate):                     2                       (  0%)
  Output Packets:                  14016892                       190917
  Output pps:                         42183
  Output Bytes:                126095746843                   1717480332
  Output Kbps (rate):               3035827                       ( 30%)

Errors Stats:
  Input  Total:                           0                            0
  Input  CRC:                             0                            0
  Input  Frame:                           0                            0
  Input  Overrun:                         0                            0
  Output Total:                           0                            0
  Output Underrun:                        0                            0

Quit='q', Freeze='f', Thaw='t', Clear='c', Interface='i',
Next='n', Prev='p'

Brief='b', Detail='d', Protocol(IPv4/IPv6)='r'

**Comment by pstavirs** [comment]
I will replace the "bytes/sec" with "bits/sec" in the stats window shortly.

Since large numbers in the stats window already use thousands separators and the k/m/g is a multiple of 1000 instead of 1024, it should be easy to fathom that number from the bits/sec number.

**Comment by jimitsalvi** [comment]
@pstavirs - That would be great. Thanks
