### ISSUE TITLE
Feature request : To see the hardware address of the traffic port from the Client application

### ISSUE THREAD

**Issue by jimitsalvi** [pstavirs/ostinato#242]
In order to obtain the hardware address of the traffic port need to login into VM console and view it. It would be more convenient to obtain this information from the client application which would help to make crafting packets a bit more efficient.

**Comment by pstavirs** [comment]
@jimitsalvi Just curious - is there a reason you **have** to use the same mac address as the host. Why not any arbitrary made up mac address? Ostinato is designed to be used independent of the underlying host interface's mac and IP addresses

**Comment by jimitsalvi** [comment]
@pstavirs - I was not aware of that fact. That being the case, I cannot think of any other reason to be able to see the hardware mac address.
