### ISSUE TITLE
Incorrect traffic rate display for 7Gbps in GUI

### ISSUE THREAD

**Issue by jimitsalvi** [pstavirs/ostinato#245]
Gui display's as generating around ~8.5Gbps (fluctuating between 6.5-8.5) traffic whereas the configured data rate is 7Gbps.

 Last input 00:00:00, output 00:00:00
  Last clearing of "show interface" counters 2d22h
  30 second input rate 6756526000 bits/sec, 91742 packets/sec
  30 second output rate 6734609000 bits/sec, 91444 packets/sec
     19912902547 packets input, 176471696931486 bytes, 0 total input drops
     4 drops for unrecognized upper-level protocol

![4](https://user-images.githubusercontent.com/22686023/34891980-8b3a5a40-f7a5-11e7-9b12-6cd7a481cdc3.PNG)

**Comment by pstavirs** [comment]
@jimitsalvi Are you using a single packet size across all your streams or is it varying? Are you using _sequential streams_ or _interleaved streams_ ?

**Comment by jimitsalvi** [comment]
@pstavirs - I am using the same packet size across all the streams of MTU 9210. I am using interleaved stream. These are simple IPV4 streams with no special configuration. I can share the configuration file if you'd like.

**Comment by pstavirs** [comment]
@jimitsalvi is this issue same as #239? If not, can you elaborate?

**Comment by jimitsalvi** [comment]
@pstavirs - This is not same as #239 . The issue here is sometimes the gui shows as generating more traffic that it is configured for. 
For e.g.: The stream is set to 7Gbps. but as per the gui, if u see it show that ostinato is generating more than it is configured for which I believe should not be the case.

**Comment by pstavirs** [comment]
@jimitsalvi Looking at the image again, I see that the 7Gbps configured tx rate is on `Port 1-0` while the 8.5Gbps is the tx rate on `Port 2-0`

**Comment by jimitsalvi** [comment]
@pstavirs - yes, I believe that should not be the case. I agree there will be some difference but this looks like a substantial one. I am not sure if I have a good explanation for why we are seeing this intermittently.

**Comment by pstavirs** [comment]
@jimitsalvi Please re-read my earlier update. You are comparing tx rates for two different ports

**Comment by pstavirs** [comment]
Closing as no response from submitter.

If you think this is a bug, please reopen.
