### ISSUE TITLE
Unable to edit one bit in the MAC address in the stream.

### ISSUE THREAD

**Issue by jimitsalvi** [pstavirs/ostinato#248]
Unable to edit the mac address in the streams. If needed to change one bit in the mac address entire trailing mac address bits needs to be deleted.

**Comment by pstavirs** [comment]
@jimitsalvi You can use the mouse to select the part you need to change.

**Comment by jimitsalvi** [comment]
That's fine. I was trying to delete the bit and write the new one.

**Comment by pstavirs** [comment]
@jimitsalvi Please provide exact steps to repro

**Comment by jimitsalvi** [comment]
1) Edit stream.
2) try to delete any one bit in the mac address using backspace or delete button (does not work)
3) if the above step would have worked, then type in the new bit.
