### ISSUE TITLE
Drone does not launch with Ostinato - cryptic error message

### ISSUE THREAD

**Issue by fredtd** [pstavirs/ostinato#252]
When launching Ostinato, receive the attached pop-up dialog.  Loaded previously created (and working) data stream. Started drone separately multiple times, but the transmit button in Ostinato remains disabled. Have also tried to copy the drone executable to the same directory as Ostinato, but unable to due to a read-only file system.
Any suggestions?
Thanks,

![screen shot 2018-03-02 at 9 08 34 am](https://user-images.githubusercontent.com/36774341/36913612-249cc39a-1e10-11e8-8ff6-3d5ed542e928.png)

Please cancel request. Error disappeared after running from command line. Now transmitting OK.

**Comment by pstavirs** [comment]
Closing since Submitter solved the problem.
