### ISSUE TITLE
OS X: Copy/Paste with Keyboard Shortcuts doesn't work

### ISSUE THREAD

**Issue by ehlers** [pstavirs/ostinato#257]
Ostinato 0.9 on OS X V10.11.6 (El Capitan)

On OS X copy and paste doesn't work with the keyboard shortcuts Command-C / Command-V. On Linux (Debian Stretch) that works as expected (with Ctrl-C / Ctrl-V).

Workaround is to right-click in the text field and select the function in the popup menu. At least for me it took a while until I thought about that. I normally use only the keyboard shortcuts.

**Comment by pstavirs** [comment]
@ehlers Where are you pasting in the Ostinato interface? If this is the Stream Config Dialog | Protocol Data | Userscript field, it works fine for me on OSX Sierra. This might be a Qt issue. Are you running Ostinato as root or via su/sudo by any chance?

**Comment by ehlers** [comment]
Yes, I'm trying to paste into the Stream Config Dialog | Protocol Data | Userscript field, here a screenshot. It's also not working in other text fields.

<img src="https://user-images.githubusercontent.com/896406/39761613-d8f29d40-52d8-11e8-907d-862f20d24fab.png" width="80%" />

As I said, that's working fine with Linux. And it working, when I right-click into the text field and select "Paste". As you can see in the screenshot this popup shows the correct keyboard shortcut Command-V for paste.

I'm running Ostinato as a regular non-admin user.

**Comment by ehlers** [comment]
I'm normally using German as the language setting in OS X, just changed it to English, but that doesn't help. And I noticed, that hitting Command-V results in this short warning tone, when using an unallocated key sequence. By testing several other key combinations I found that Fn-Command-V works. Really strange. Maybe we delay it and test again with QT5.

**Comment by ehlers** [comment]
Just noticed, that "Edit" is not shown in the Ostinato menu bar. That's where normally Cut, Paste, Undo, Redo, ... are defined. But that's also not shown in Linux, where I have no issues.
![ostinato_menu](https://user-images.githubusercontent.com/896406/39763614-ef9803b4-52dd-11e8-8977-ba66536b4c9b.png)

**Comment by pstavirs** [comment]
The `Edit` menu is not present because I did not put it there. But that should not affect the copy-paste shortcuts.

As for Qt5 - the latest code is now based on Qt5 (Qt4 is no longer supported) - so you can try building from source.

**Comment by ehlers** [comment]
Setting up a build environment for Ostinato on OS X is currently too much work for me. Maybe later.
