### ISSUE TITLE
QT5/OSX: Scrolling in Add/Edit Stream broken

### ISSUE THREAD

**Issue by ehlers** [pstavirs/ostinato#261]
OS X 10.11.6 (El Capitan), Ostinato master (e1194a1), QT5 v5.10.1 installed by homebrew, Protobuf v3.5.1 installed by home-brew

OSX-QT5-Patches applied, see https://github.com/pstavirs/ostinato/issues/258

The whole Add/Edit Stream dialog box seems to have broken scrolling on OS X.  That doesn't happen with QT4. Also when building on Debian Linux with QT 5.7 I haven't noticed that issue. 

In "Protocol Data" the "Internet Protocol ver 4" part scrolls extremely choppy.

Sometimes the Protocol Selection / Simple gets garbled after some scrolling. And it stays that way until a new scrolling action is started.

![simple_protocol_selection](https://user-images.githubusercontent.com/896406/39968514-3287ee02-56ce-11e8-81ee-e82d607dfb54.png)

**Comment by ehlers** [comment]
Just compiled with QT 5.9.3 and that works as well. Then re-tested with 5.10.1, this time with installed Xcode. That still has the scrolling issue, so installing Xcode doesn't make a difference.

**Comment by pstavirs** [comment]
@ehlers I would recommend using Qt 5.9 as that is the LTS release

**Comment by ehlers** [comment]
Sure, originally I used 5.10.1 as it's quite difficult in Homebrew to install earlier versions. After I mastered that I will keep version 5.9.

Close it?

**Comment by pstavirs** [comment]
Closing as this is a Qt issue, not Ostinato issue
