### ISSUE TITLE
"Show My Reservered Ports Only" not saved to config

### ISSUE THREAD

**Issue by hansfn** [pstavirs/ostinato#270]
Testing latest version from Git, I notice that "Show My Reserved Ports Only" isn't saved to config. It's not saved as a part of the session either. Maybe that is better?

Use case: I'm (ab)using the reservation in the port configuration (together with "Show My Reservered Ports Only") to hide ports that have no traffic or are irrelevant. Maybe there is a better way?

**Comment by pstavirs** [comment]
@hansfn When you say "config" what do you mean? The "session" file when you save it? Yes, at this time it is not saved as part of the session. I'm not sure if it should be considered as part of session or not. I'll let others comment here one way or other on the same.

Regarding your use case, if you never plan on using those ports, see if [PortList filtering][https://userguide.ostinato.org/Settings.html#portlist] might be better suited for you.

**Comment by hansfn** [comment]
Thx a lot for the Drone settings link - PortList filtering was just what I needed. Feel free to close this issue.

When I say that it isn't store to config, I meant to Ostinato.conf where the preferences (like path to wireshark and so) is stored.

**Comment by pstavirs** [comment]
Closing. If anyone else feels strongly about this issue, feel free to reopen with justification
