### ISSUE TITLE
Build fails under Windows

### ISSUE THREAD

**Issue by tan-wei** [pstavirs/ostinato#277]
It seems that some extra modifications should be done before building under windows.

I have added `protoc` and `protobuf` include and library directories. But `protoc` procedure fails with the following error message:
```
	C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
	protoc --cpp_out=. --proto_path=. ..\..\ostinato\common\protocol.proto
..\..\ostinato\common\protocol.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
```

Is there anything wrong with my env? Thanks!

**Comment by pstavirs** [comment]
@tan-wei Please use the MINGW toolchain to compile Ostinato on Windows

**Comment by tan-wei** [comment]
Sorry, I find the documents in the website. MinGW works for me now. Thanks for your reply.

**Comment by muse117** [comment]
I have the same problem. I use mingw to compile protobuf.
![微信截图_20200903150653](https://user-images.githubusercontent.com/9733486/92082599-59f2a280-edf7-11ea-9a32-a57d89eab33b.png)

**Comment by typzzh** [comment]
> Sorry, I find the documents in the website. MinGW works for me now. Thanks for your reply.

where is the document?
