### ISSUE TITLE
Crash when opening session

### ISSUE THREAD

**Issue by b-ehlers** [pstavirs/ostinato#281]
Version: master branch, rev 3e46c1b99103
OS: macOS v10.13.6 (High Sierra)
QT: 5.12.3 from homebrew

Opening a session (File / Open Session) works fine, when no port is selected. But when a port is selected and I open a session, Ostinato crashes. Sometimes it works on the first try, but crashes on the second or third attempt. But it's important to select a port.

Tested also with Debian Buster, same issue.

[ostinato.log.txt](https://github.com/pstavirs/ostinato/files/3524706/ostinato.log.txt)

**Comment by pstavirs** [comment]
@b-ehlers Thanks for reporting the issue. I can confirm that I am able to reproduce the issue. The crash is happening inside malloc() called by Qt code - that's possibly a red-herring and the actual problem's elsewhere.

Still debugging.

**Comment by pstavirs** [comment]
@b-ehlers Looks like this was a regression caused by a recent commit. I don't understand why the code changes in the offending commit would cause a crash, but for now I've reverted the offending commit. Appreciate if you could confirm you are not seeing the problem anymore. Thanks in advance!

**Comment by b-ehlers** [comment]
Confirmed - issue is resolved, tested both with macOS and Debian Linux.
