### ISSUE TITLE
Specifying Wireshark.app path in Preferences on MacOS does not work

### ISSUE THREAD

**Issue by pstavirs** [pstavirs/ostinato#288]
This is because Ostinato expects the actual executable i.e. `/Applications/Wireshark.app/Contents/MacOS/Wireshark` - but the file picker UI does not allow drilling down into an application bundle and the Preferences UI does not allow directly entering the full path

If user gives a .app as the path, Ostinato should use the `plist.info` to find the executable name and use the full path to that instead.

**Comment by b-ehlers** [comment]
Workaround, tested on macOS 10.13.6 (High Sierra):

The file picker uses the same shortcuts as the Finder, so `Shift-Command-G` opens a text entry field to enter a directory.

Then you can
- enter a path manually
- use `right-click Paste` to paste a path
- drag a directory from the Finder into the text entry

I prefer to clear the text entry, use the Finder to go into the Wireshark application bundle, then drag the `Contents` directory into the entry field and open that. After that I open the `MacOS` directory, then select `Wireshark.app`.

**Comment by pstavirs** [comment]
Another workaround - create a softlink to the actual executable inside the application bundle -
```
ln -s wireshark /Applications/Wireshark.app/Contents/MacOS/Wireshark
```
and use the Preferences file picker UI to select the softlink

**Comment by b-ehlers** [comment]
Nice finding. But I would swap the arguments, the last argument is the softlink.

Instead
> ```
> ln -s wireshark /Applications/Wireshark.app/Contents/MacOS/Wireshark
> ```
```
ln -s /Applications/Wireshark.app/Contents/MacOS/Wireshark wireshark
```
