### ISSUE TITLE
Jumbo Frames message multiplied in Preflight Check

### ISSUE THREAD

**Issue by biggena** [pstavirs/ostinato#290]
Ostinato version is 1.0, Docker.

When trying to generate frames with increment I have following message for size 1523 (6 messages in one alarm):
![image](https://user-images.githubusercontent.com/40003342/70112940-e6511880-165f-11ea-9ee1-3dabf184e7dd.png)

For size 1524 it is 12 messages in one screen, etc. Each extra byte produces 6 extra messages in this window.
Starting from some number it just doesn't fit the screen, so buttons are invisible:
![image](https://user-images.githubusercontent.com/40003342/70112968-f9fc7f00-165f-11ea-91a8-6754f634bf43.png)

Workaround: I proceed with this warning (despite OK button is not seen on the screen) by pressing "Tab" key and "Enter" when this window appears.

Feature enchancements: Would it be possible to add choice to disable such check permanently in preferences in newer Ostinato versions?

**Comment by pstavirs** [comment]
@biggena : I've fixed the multiple error message issue which was a bug - it should have been reported only once despite however many frames may experience that issue. Regarding a disable check option - how big of a nuisance is it? My worry is that if a user disables that check, he may not realize that some change that he made in the stream may cause other errors without the error check.

**Comment by biggena** [comment]
@pstavirs Thank you for fixing, when it will be available in some minor release version?
About option to disable such check - I find quite annoying getting a lot such messages during a testing day, especially when I know that I"m working with Jumbo frames. You can embed such option in Preference, but keep it disabled. Only experienced user will enable it and escape some extra warnings... Thank you.

**Comment by pstavirs** [comment]
@biggena : thanks for the quick reply. Your annoyance is regarding just the jumbo frames error message or other messages also? The reason I ask is if it is just jumbo, I might think of other ways to avoid the errors e.g. by checking interface MTU directly and not reporting the error if the MTU > packet size.

Regarding the new minor release, I need to collect several bugfixes before I can issue a minor release. Release making is very time consuming and needs to be thoroughly tested to make sure no major bugs are introduced - all of it needs to be done on multiple platforms as well, so realistically it will be a couple of months most likely.

**Comment by biggena** [comment]
@pstavirs My annoyance was only about permanent jumbo frames warnings, if you can avoid it by checking interface MTU - it will work, great idea!
Thank you and Happy New Year!

**Comment by pstavirs** [comment]
@biggena : I filed #296 to track the jumbo check against interface MTU. Warning - it may take some time to implement that as it will likely need platform specific code for each platform.
