### ISSUE TITLE
Unexpected behavior in GUI while applying Source List address in IGMPv3 Report

### ISSUE THREAD

**Issue by biggena** [pstavirs/ostinato#292]
It is not possible to apply Source List address in IGMPv3 Report. When editing default address 0.0.0.0 and changing it to some other address, like 10.10.10.10, and applying it via OK button - result will be 0.0.0.0.
Only adresses which contain 3 digits in each octet can be applied properly, like 100.100.101.102, etc.
Also using leading 0 before digits causes unexpected behaviour, like 010.011.012.013 transforms to address 8.9.10.11 after applying.
Ostinato v1.0

**Comment by pstavirs** [comment]
This seems to be due to a behaviour change between Qt4 and Qt5. Will investigating further ...
