### ISSUE TITLE
IGMPv3 report, allow Increment/Decrement for Group Address/Source List

### ISSUE THREAD

**Issue by biggena** [pstavirs/ostinato#293]
It would be great for scale testing to have option to allow Increment/Decrement for Group Address/Source List in IGMPv3 report.
Currently those fields are fixed:
![image](https://user-images.githubusercontent.com/40003342/70627599-2e0f0b80-1c2f-11ea-88ec-c596b5ee2e85.png)
And for scale testing it is needed to create separate streams, which is not convenient and doesn't allow to test large amount of groups:
![image](https://user-images.githubusercontent.com/40003342/70627835-9f4ebe80-1c2f-11ea-95c6-125cacef59e9.png)

**Comment by pstavirs** [comment]
@biggena: Please use [Variable Fields](https://userguide.ostinato.org/StreamConfig.html#variable-fields). Because of the multi-record nature of IGMPv3, you might have to use the "custom" field with an offset to specify the group and source addresses.

Let me know if it solves your problem.

**Comment by biggena** [comment]
@pstavirs : Thank you, it works like a charm!
This is result from Wireshark:
![image](https://user-images.githubusercontent.com/40003342/70704371-8818db00-1cda-11ea-8d80-933685fcbf23.png)
This is how Variable Fields were used:
![image](https://user-images.githubusercontent.com/40003342/70704493-c1514b00-1cda-11ea-8268-9b27fd310624.png)

**Comment by pstavirs** [comment]
@biggena Glad to know it worked!

**Comment by pstavirs** [comment]
@biggena Glad to know it worked!
