### ISSUE TITLE
Endpoint doesn't reply to ARP request which has Priority 6 in 802.1q header

### ISSUE THREAD

**Issue by biggena** [pstavirs/ostinato#295]
Please solve issue with endpoint ignoring ARP requests with Priority 6 in 802.1q header.
Such ARPs generate Huawei routers I had to interoperate with today.
Besides Priority field Huawei also uses 70 bytes long ARP frames (not counting FCS).
To investigate this I generated two types of ARPs: 
- 70 bytes long with default 802.1q Priority 0 (frames 1859, 1861)
- 70 bytes long with 802.1q Priority 6 (frames 2130, 2132)
First type got response from Ostinato Endpoint (10.249.0.10), but not the second.

![Screenshot from 2019-12-18 16-51-35](https://user-images.githubusercontent.com/40003342/71100345-88731380-21bd-11ea-8dca-254487ab0e13.png)

Endpoint 10.249.0.10:
![L3_8 1 proper 2019-12-18 15-47-39](https://user-images.githubusercontent.com/40003342/71100565-ee5f9b00-21bd-11ea-89b4-18747a32e1ac.png)

Is it possible to patch Ostinato somehow to get it working? Tomorrow I have to proceed with tests, but system is not working as expected.....

**Comment by pstavirs** [comment]
@biggena : I found the problem and will fix it shortly. A question - is the ARP reply also supposed to contain the same 802.1q priority? It will of course contain the same vlan id, but I think having the same prio set in reply should not be required as each node in the network is typically free to set its own priorities. Thoughts?

**Comment by biggena** [comment]
@pstavirs In captures I see that ARP reply with priority 0 was enough for Huawei who ARP requested with priority 6. I can suppose that for other devices it will be valid too, so you don't have to send ARP reply with the same priority, it can be independent (0).

**Comment by pstavirs** [comment]
Fixed by 69772786541aebf09d95df1386189e854c18c460

**Comment by pstavirs** [comment]
The fix is incomplete. Reopening the issue

**Comment by pstavirs** [comment]
Till the time this is fixed properly, please try the following workaround -

1. For device groups with vlan, set Vlan Priority to 6 in device group vlan configuration
2. For all vlan tagged streams, set Vlan Priority to 6 in stream configuration
3. Click Apply
4. Clear ARP
5. Resolve ARP
6. Refresh Device Information to check if ARP resolution is successful or not

Repeat the above steps for all ports

@biggena : can you check if the above works for you?

**Comment by biggena** [comment]
@pstavirs Unfortunately I can't verify workaround provided as I finished tests with Huawei and don't have access to Huawei equipment.

**Comment by pstavirs** [comment]
@biggena No problem.

**Comment by pstavirs** [comment]
Commit 9934060216e redoes the fix and it is now complete.
