### ISSUE TITLE
Some Redirections from jump.ostinato.org use HTTP

### ISSUE THREAD

**Issue by b-ehlers** [pstavirs/ostinato#307]
The jump host jump.ostinato.org is accessed from ostinato by HTTPS (good), but some of its URLs redirect to HTTP destinations, which will then redirect to the final HTTPS destination.

As far as I tested https://jump.ostinato.org/download, noports, pcapdiff and winpcap are affected.

**Comment by pstavirs** [comment]
@b-ehlers Thanks for reporting the issue. I have changed all the jumphost target URLs to https now. Please let me know if you still see the issue.

**Comment by b-ehlers** [comment]
Fixed, all junp host targets I tested redirect now to HTTPS URLs.
