### ISSUE TITLE
version.pri cannot generate version.cpp in windows

### ISSUE THREAD

**Issue by muse117** [pstavirs/ostinato#316]
hi, 
APP_REVISION = $(shell git rev-parse --short=12 --verify HEAD)
shell is not a windows command

**Comment by pstavirs** [comment]
`qmake` will expand $shell suitably for windows

**Comment by muse117** [comment]
> `qmake` will expand $shell suitably for windows

I'm using qmake, but don‘t generate version.cpp

**Comment by pstavirs** [comment]
I'm sorry, I wasn't entirely clear.

`qmake` will expand `$shell` appropriately for Windows/MacOS/Linux when it generates the `Makefile`. Running `make` will generate `version.cpp`

**Comment by pstavirs** [comment]
No response. Closing for now. Reopen if needed.
