### ISSUE TITLE
ostinato doesn't remember additional port groups

### ISSUE THREAD

**Issue by anubisg1** [pstavirs/ostinato#320]
1 - add a new port group to ostinato
2 - close ostinato
3 - open ostinato

The previously added port group disappear

---

expected behaviour is to have ostinato to save in it's configuration any port group changes.
This is very important when running ostinato UI on a machine (for example your laptop) while the drone is running a linux-server directly connected to the DUT.

**Comment by pstavirs** [comment]
For now save your session as a file and use that session file to restore.

I'll look into saving session by default - or at least have a setting for the same.

**Comment by anubisg1** [comment]
Thank you.
even having an ostinato.ini file where port-groups are saved (or remote servers) would be enough i think

**Comment by pstavirs** [comment]
I've thought a bit about this and I prefer to open a 'blank slate' by default. Doing that is better for people esp. for beginners who try various things, mess up stuff and want to get back to a clean state - so they close and reopen the app. The new session doesn't have any remnants of the previous session.

One option could be to have a user preference to _remember_ and _restore_ the last session and have it _disabled_ by default.

**Comment by anubisg1** [comment]
What about the ability to add a list of portgroups I want connected at startup to be configured into an Ostinato.ini file instead? No ui changes, but if a portgroup is in the config file then I connect to it

**Comment by anubisg1** [comment]
Or, in the ui.

Preserences - - > drones

Open a window where is possible to configure additional drones and select a bool for connect at startup.

That could be then saved in Ostinato.ini

**Comment by pstavirs** [comment]
> What about the ability to add a list of portgroups I want connected at startup to be configured into an Ostinato.ini file instead?
A session file serves the same purpose and you can pass the file name to Ostinato on the command line at startup. If not on the command line, you could use `File | Open Streams` to open the session file.

Or am I missing something here?

**Comment by anubisg1** [comment]
Ok, I miss understood you then.

**Comment by pstavirs** [comment]
No worries. Closing the issue.

**Comment by anubisg1** [comment]
So, do I understand that this will be implemented in 1.2?

Thank you btw

**Comment by pstavirs** [comment]
Session Files are already supported. 

To save the session -
* Open Ostinato.
* Add all the portgroups you want using `File | Add PortGroup` 
* Save the session using `File | Save Session`
* Close Ostinato

To restore the session -
* Open Ostinato passing the session file on the command line
OR
* Open Ostinato and use `File | Open Session`
