### ISSUE TITLE
Wrong formatting of MAC address in Protocol Data / Spanning Tree Protocol

### ISSUE THREAD

**Issue by b-ehlers** [pstavirs/ostinato#340]
Ostinato v1.1 / Linux / QT5 v5.15.2

I imported a STP packet from a PCAP file [stp.pcap.zip](https://github.com/pstavirs/ostinato/files/6332227/stp.pcap.zip). The import runs without any issues.

But in Protocol Data the MAC address in the Spanning Tree Protocol section looks strange, correct is `0C:A2:8F:87:1D:00`.
![STP_protocol_data](https://user-images.githubusercontent.com/49040325/115161272-16565b80-a09d-11eb-807a-d729762fb025.png)

In Paket View the packet is correct, so that's not an import issue.
![STP_packet_view](https://user-images.githubusercontent.com/49040325/115161287-240be100-a09d-11eb-8473-1672f31d67bd.png)

After some head scratching I found, that this is a formatting issue. The correct MAC address `0C:A2:8F:87:1D:00` is shown as `CA 28 F8 71 D0 0`. The leading zero is dropped, what results in a MAC address, that looks completely different.

**Comment by pstavirs** [comment]
@b-ehlers : Could you attach the pcap packet that you imported?

**Comment by b-ehlers** [comment]
> @b-ehlers : Could you attach the pcap packet that you imported?

I did in the initial comment.

> I imported a STP packet from a PCAP file [stp.pcap.zip](https://github.com/pstavirs/ostinato/files/6332227/stp.pcap.zip).

This zip file stp.pcap.zip contains the pcap file you are asking for.

**Comment by pstavirs** [comment]
Thanks - sorry, failed to notice that.
