### ISSUE TITLE
In Ubuntu 18.04, protoc cannot find the proto file in the same directory

### ISSUE THREAD

**Issue by kittener** [pstavirs/ostinato#341]
ostinato-1.1/common/protocol.proto:-1: error: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).

**Comment by pstavirs** [comment]
Save the **full output** of the compiler in a file and attach it here for analysis

**Comment by kittener** [comment]
[full output.md](https://github.com/pstavirs/ostinato/files/6359598/full.output.md)
so kind of you

**Comment by pstavirs** [comment]
Looks like you are using QtProject.

Use command line qmake and make.

Srivats

**Comment by kittener** [comment]
wow, that's great!!! :D
