### ISSUE TITLE
1.3 Port Statistics no longer works with Show My Reserved Ports Only

### ISSUE THREAD

**Issue by Takalele** [pstavirs/ostinato#367]
Hi,

with the new version 1.3 the reserved ports dont show up in the Port Statistics when "Show My Reserved Prots Only" is on.

I've tested it on Windows and Linux both have the same issue.
1.3:
![ostinato-1 3](https://github.com/pstavirs/ostinato/assets/22237036/609d2ad8-a702-40f7-af64-3fc9db1e7e5c)

1.2:
![ostinato-1 2](https://github.com/pstavirs/ostinato/assets/22237036/7a6464cd-a239-4caf-af49-38127424c572)

BR
Takalele

**Comment by pstavirs** [comment]
Yes, unfortunately this is a regression introduced in 1.3.0

Details in this blog post - https://srivatsp.com/ostinato/ostinato-port-stats-ui/

Fixed in 483f7fb4c5badf42a4652f09aec8ad769f8f9779

**Comment by Takalele** [comment]
Hi,

thank you.

BR
Takalele
