### ISSUE TITLE
ostinato build issues with Qt5.15.2 MinGW 32-bit.

### ISSUE THREAD

**Issue by typzzh** [pstavirs/ostinato#370]

**Comment by typzzh** [comment]
error: cast between incompatible function types from 'FARPROC' {aka 'int (__attribute__((stdcall)) *)()'} to 'DWORD (__attribute__((stdcall)) *)(const GUID*, PNET_LUID)' {aka 'long unsigned int (__attribute__((stdcall)) *)(const _GUID*, _NET_LUID*)'} [-Werror=cast-function-type]      hDll ? reinterpret_cast<decltype(&function)> (GetProcAddress(hDll, #function)) : NULL;

**Comment by pstavirs** [comment]
Please share the full build log.

FYI, the build instructions are at https://devguide.ostinato.org/build-instructions/

**Comment by typzzh** [comment]
[ostinato_compile.txt](https://github.com/pstavirs/ostinato/files/14127044/ostinato_compile.txt)
portmanager.cpp: In member function 'pcap_if_t* PortManager::GetPortList()':
portmanager.cpp:45:82: error: cast between incompatible function types from 'FARPROC' {aka 'int (__attribute__((stdcall)) *)()'} to 'DWORD (__attribute__((stdcall)) *)(const GUID*, PNET_LUID)' {aka 'long unsigned int (__attribute__((stdcall)) *)(const _GUID*, _NET_LUID*)'} [-Werror=cast-function-type]
     hDll ? reinterpret_cast<decltype(&function)> (GetProcAddress(hDll, #function)) : NULL;
                                                                                  ^
portmanager.cpp:180:22: note: in expansion of macro 'MyGetProcAddress'
     auto guid2Luid = MyGetProcAddress(ipHlpApi_, ConvertInterfaceGuidToLuid);
                      ^~~~~~~~~~~~~~~~
portmanager.cpp:45:82: error: cast between incompatible function types from 'FARPROC' {aka 'int (__attribute__((stdcall)) *)()'} to 'DWORD (__attribute__((stdcall)) *)(const NET_LUID*, PWSTR, SIZE_T)' {aka 'long unsigned int (__attribute__((stdcall)) *)(const _NET_LUID*, wchar_t*, long unsigned int)'} [-Werror=cast-function-type]
     hDll ? reinterpret_cast<decltype(&function)> (GetProcAddress(hDll, #function)) : NULL;
                                                                                  ^
portmanager.cpp:181:23: note: in expansion of macro 'MyGetProcAddress'
     auto luid2Alias = MyGetProcAddress(ipHlpApi_, ConvertInterfaceLuidToAlias);
                       ^~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors

**Comment by typzzh** [comment]
@pstavirs  Now I encountered following building problems in windows.     cannot find -lprotobuf

mingw32-make[2]: Entering directory 'C:/cppqt/ostinato/server'
g++ -static -Wl,-subsystem,console -mthreads -o debug\drone.exe @object_script.drone.Debug  -lwpcap -lpacket -liphlpapi -L..\common\debug -lostproto -L..\rpc\debug -lpbrpc -lm -LC:\cppqt\protobuf-cpp-3.20.2\build -lprotobuf C:\Qt\5.15.2\mingw81_32\lib\libQt5Network.a C:\Qt\5.15.2\mingw81_32\lib\libQt5Script.a C:\Qt\5.15.2\mingw81_32\lib\libQt5Xml.a C:\Qt\5.15.2\mingw81_32\lib\libQt5Core.a   
C:/Qt/Tools/mingw810_32/bin/../lib/gcc/i686-w64-mingw32/8.1.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lprotobuf
collect2.exe: error: ld returned 1 exit status
mingw32-make[2]: *** [Makefile.drone.Debug:159: debug/drone.exe] Error 1
mingw32-make[2]: Leaving directory 'C:/cppqt/ostinato/server'
mingw32-make[1]: *** [Makefile.drone:45: debug] Error 2
mingw32-make[1]: Leaving directory 'C:/cppqt/ostinato/server'
mingw32-make: *** [Makefile:88: server-make_first] Error 2
mingw32-make: *** Waiting for unfinished jobs....

**Comment by typzzh** [comment]
Thanks pstavirs! good idea !
