### ISSUE TITLE
Add support for MPLS labels

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pstavirs/ostinato#76]
```
We need to generate ethernet frames with mpls labels instead of vlan tags

```

Original issue reported on code.google.com by `slypi...@gmail.com` on 29 Aug 2012 at 5:41

**Comment by pstavirs** [comment]
See -

[How to generate MPLS packets using Hexdump](https://srivatsp.com/ostinato/ostinato-mpls-hexdump/)
[How to generate MPLS packets using User Script](https://srivatsp.com/ostinato/ostinato-mpls-userscript/)

If native support is desired, update this issue with rationale and I'll reconsider
